#include<iostream>
using namespace std;
// Today we are going to studied about the scope resolution opeerator which is represented by the symbol "::"....
// There are many uses ofthis operator so some we will discuss today ...

// 1..It is used to declare the global variable inside the main function when the  local variable is alredy present in the main func.
// and if both local and the global variable having the same name ...

int tej;   // here we have created the global variable ....
int main(){
    int tej=10;   // here we have created the local variable 
    ::tej = 122;
    // here we are assigning the global variable value... 
    cout<<"The value of the global variable is : "<<::tej<<endl;
    // Here we are printing the global variable ...using the scope resolution operator ...... 
    cout<<"the value of the local variable is : "<<tej<<endl;
    // Here we are printing the local variable value normally....   
}

// 2..It is also used to declare the function outside the class.....
// It canbe used to deaclare the static member value outside the class.....
//It is used in the case of the multiple inheritance .....
// It is used for te namespace.....

//reference for other example ...

//https://www.geeksforgeeks.org/scope-resolution-operator-in-c/
